// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR6H1JWzQd7dk5YdbEMH4qQXooMXa2T_o',
    appId: '1:561624867349:web:53b160959d52ee0256641c',
    messagingSenderId: '561624867349',
    projectId: 'voicecalltest-b2495',
    authDomain: 'voicecalltest-b2495.firebaseapp.com',
    storageBucket: 'voicecalltest-b2495.firebasestorage.app',
    measurementId: 'G-GFH4XXBP4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdHfl-w1dtgy5Uc01HrFjJ06V4xwD6Ft4',
    appId: '1:561624867349:android:fa2649f7502c7b9156641c',
    messagingSenderId: '561624867349',
    projectId: 'voicecalltest-b2495',
    storageBucket: 'voicecalltest-b2495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPy3WdymC73gVFEshu1jpFyO_DnmSDuyc',
    appId: '1:561624867349:ios:e4b49bfe9dce5d6856641c',
    messagingSenderId: '561624867349',
    projectId: 'voicecalltest-b2495',
    storageBucket: 'voicecalltest-b2495.firebasestorage.app',
    iosBundleId: 'com.example.agoratestin1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPy3WdymC73gVFEshu1jpFyO_DnmSDuyc',
    appId: '1:561624867349:ios:e4b49bfe9dce5d6856641c',
    messagingSenderId: '561624867349',
    projectId: 'voicecalltest-b2495',
    storageBucket: 'voicecalltest-b2495.firebasestorage.app',
    iosBundleId: 'com.example.agoratestin1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR6H1JWzQd7dk5YdbEMH4qQXooMXa2T_o',
    appId: '1:561624867349:web:42c74434ac3dc4f856641c',
    messagingSenderId: '561624867349',
    projectId: 'voicecalltest-b2495',
    authDomain: 'voicecalltest-b2495.firebaseapp.com',
    storageBucket: 'voicecalltest-b2495.firebasestorage.app',
    measurementId: 'G-8FSVBNYGT1',
  );
}
